### ISSUE TITLE
Screen width does not match original on the login page

### ISSUE THREAD

**Issue by mmoayyed** [rallportctr/cas#1]
Compare with http://jasigcas.herokuapp.com/login

**Comment by rallportctr** [comment]
Corrected screen width for Login page. The current link displays an application error screen as shown in the image below:

![screen shot 2015-08-12 at 12 04 24 pm](https://cloud.githubusercontent.com/assets/13034090/9229294/6239f2fa-40ea-11e5-8036-e496695e6821.png)

**Comment by mmoayyed** [comment]
Try again now please. Sometimes the heroku instance goes to sleep and we literally need to wake it up. part of the free package is that it needs to sleep for 6 hours.

**Comment by rallportctr** [comment]
Screen width adjusted to match  http://jasigcas.herokuapp.com/login
