### ISSUE TITLE
Placement of "Kill" option

### ISSUE THREAD

**Issue by mmoayyed** [rallportctr/cas#10]
As it stands today, the Kill option seems to apply to ALL SSO sessions for a given user. That is fine, but we also need to kill individual tickets. A user may have 3 sessions, and you may only want to kill one out of 3. So there should be kill buttons every time you see a TGT-xxxxx

**Comment by rallportctr** [comment]
The idea was to have the "lightning bolt" (under Kill label) be the KILL button for individual sessions. Would it be possible to have someone code this?

**Comment by mmoayyed** [comment]
Sure. Either Adam, or Jeff may pick this up.
