### ISSUE TITLE
Add Search capabilities

### ISSUE THREAD

**Issue by mmoayyed** [rallportctr/cas#12]
Allow the user to search for data. We should be able to search by the following:
1. User id
2. Ticket id

and have additional filters for authentication date and ticket count, proxy tickets only, etc.

**Comment by rallportctr** [comment]
We can use DataTables for this, however, it may take a little bit to construct unless someone in the team knows DataTables well (Developer needed for Datatables implementation)

https://datatables.net/examples/api/multi_filter.html
