### ISSUE TITLE
Principal Attributes need to turn into a table

### ISSUE THREAD

**Issue by mmoayyed** [rallportctr/cas#15]
Principal attributes are a map, where the key is a single value, and the value is an array. The screen should adjust to note that. Maybe the row turns into an inner table?

**Comment by rallportctr** [comment]
We can use DataTables for this, however, it may take a little bit to construct unless someone in the team knows DataTables well (Developer needed for Datatables implementation)

This will go well with the other issue regarding sorting/filtering, etc
http://datatables.net/examples/api/row_details.html
