### ISSUE TITLE
Username/Password fields must align with upper elements

### ISSUE THREAD

**Issue by mmoayyed** [rallportctr/cas#4]
Seems like the fields are stretched a bit too far to the the list. They should be left aligned with "Enter your Username and Password" and the box right above. 

Compare with http://jasigcas.herokuapp.com/login

Also "Enter your Username and Password" should show as bold. Seems like it's grayed out.

**Comment by rallportctr** [comment]
Reverted to original styling
Left aligned with "Enter your Username and Password" and the box right above.
Bolded text - "Enter your Username and Password"
