### ISSUE TITLE
"Log In Successful" does not match original style

### ISSUE THREAD

**Issue by mmoayyed** [rallportctr/cas#6]
When you login successfully with casuser/Mellon, "Log In Successful" should show as bold. It's probably related to other styling issues.

**Comment by mmoayyed** [comment]
If you look at the "statistics" endpoint, you'll see all header titles have shrunk down in size and color.

**Comment by rallportctr** [comment]
Reverted to original styling
"Log In Successful" shows as bold and other styling reverted also.
