### ISSUE TITLE
Separate ticket blocks on the SSO sessions screen

### ISSUE THREAD

**Issue by mmoayyed** [rallportctr/cas#9]
If I have multiple blocks of data added to the table, it's very difficult to figure out which is which, where one starts and where one ends. We need to provide clear distinctions between these blocks. 

Also, perhaps in order to save screen real state, you could just show a heading for each block, and then when I click on it, expand it down to show additional fields.

**Comment by rallportctr** [comment]
[Comment added for tracking - work in progress]
Per the screenshot, each session is shown as a different entity (block). I will make the distinction clearer. 
![screen shot 2015-08-12 at 3 20 54 pm](https://cloud.githubusercontent.com/assets/13034090/9234278/d905e216-4105-11e5-82f0-3b29760d43df.png)

**Comment by rallportctr** [comment]
Added larger spacing between sessions
<img width="925" alt="screen shot 2015-08-19 at 8 57 31 am" src="https://cloud.githubusercontent.com/assets/13034090/9356691/6fa7af3e-4650-11e5-9bb2-66ab930779e3.png">
space between session instances
